import type { NextPage } from "next";
import Head from "next/head";
import useSWR from "swr";
import { apiRes, Weapon, Weapons } from "../src/models/weaponModel";
import styles from "../styles/Home.module.css";

const fetcher = (url: string) => {
  return fetch(url).then((r) => r.json());
};

const Home: NextPage = () => {
  const { data, error } = useSWR<apiRes>("/api/valorant-weapons", fetcher);
  if (error) console.log(error);
  if (data) console.log(data);

  if (!data) return <></>;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {data.weapons.data.map((x) => {
          return (
            <li key={x.uuid}>
              <img src={x.displayIcon} />
            </li>
          );
        })}
      </main>
    </div>
  );
};

export default Home;
